// dither-next/src/shared/ui/Segmented.tsx
"use client";

import { cn } from "@/shared/lib";

export interface SegmentedProps<T extends string | number> {
  options: readonly T[];
  value: T;
  label?: string;
  onChange?: (value: T) => void;
}

/**
 * Segmented — a row of mutually-exclusive buttons. Verbatim port of
 * `src/shared/ui/Segmented.vue`.
 *
 * `v-model` → `value` / `onChange` (guide §4). Generic over `T extends
 * string | number` like the Vue SFC's `<script setup generic>`.
 */
export function Segmented<T extends string | number>({
  options,
  value,
  label,
  onChange,
}: SegmentedProps<T>) {
  return (
    <div className="flex items-center gap-2">
      {label ? (
        <span className="w-14 shrink-0 whitespace-nowrap text-[11px] text-muted-foreground">
          {label}
        </span>
      ) : null}
      <div className="flex flex-1 flex-wrap rounded-md border border-border bg-background/60 p-0.5">
        {options.map((opt) => (
          <button
            key={String(opt)}
            type="button"
            className={cn(
              "rounded-[5px] px-2 py-1 text-[11px] leading-none transition-colors",
              opt === value
                ? "bg-accent text-accent-foreground"
                : "text-muted-foreground hover:text-foreground",
            )}
            onClick={() => onChange?.(opt)}
          >
            {opt}
          </button>
        ))}
      </div>
    </div>
  );
}

// src/shared/ui/Segmented.vue
<script setup lang="ts" generic="T extends string | number">
defineProps<{
  options: readonly T[]
  modelValue: T
  label?: string
}>()
const emit = defineEmits<{ "update:modelValue": [T] }>()
</script>

<template>
  <div class="flex items-center gap-2">
    <span
      v-if="label"
      class="w-14 shrink-0 whitespace-nowrap text-[11px] text-muted-foreground"
      >{{ label }}</span
    >
    <div
      class="flex flex-1 flex-wrap rounded-md border border-border bg-background/60 p-0.5"
    >
      <button
        v-for="opt in options"
        :key="String(opt)"
        type="button"
        class="rounded-[5px] px-2 py-1 font-mono text-[11px] leading-none transition-colors"
        :class="
          opt === modelValue
            ? 'bg-accent text-accent-foreground'
            : 'text-muted-foreground hover:text-foreground'
        "
        @click="emit('update:modelValue', opt)"
      >
        {{ opt }}
      </button>
    </div>
  </div>
</template>
