// src/widgets/toolbar/Toolbar.vue
<script setup lang="ts">
import { ref, watch } from "vue"
import {
  addArtboard,
  duplicateSelected,
  editor,
  groupSelected,
  removeSelected,
  replay,
  selectedArtboard,
  ungroup,
} from "@/entities/editor"
import { history, redo, undo } from "@/features/history"
import { exportArtboardPng } from "@/features/export-image"
import { exportDocument, importDocument } from "@/features/persistence"
import { addArtboardFromPreset, presets } from "@/features/presets"
import type { ArtboardKind } from "@/entities/artboard"
import { CHART_TYPES } from "@/shared/config"
import { useTheme } from "@/shared/lib"

const emit = defineEmits<{ export: [] }>()
const { dark, toggle } = useTheme()
const addOpen = ref(false)
const fileInput = ref<HTMLInputElement | null>(null)

async function onOpenFile(e: Event) {
  const input = e.target as HTMLInputElement
  const file = input.files?.[0]
  if (file) await importDocument(file)
  input.value = ""
}
const canData = () => !!selectedArtboard.value && !selectedArtboard.value.widget

const pngBusy = ref(false)
async function onPng() {
  const a = selectedArtboard.value
  if (!a || pngBusy.value) return
  pngBusy.value = true
  await exportArtboardPng(a, 2)
  pngBusy.value = false
}

// Dismiss the add-menu on outside click / Escape (same pattern as ContextMenu).
const closeAdd = () => (addOpen.value = false)
const onAddKey = (e: KeyboardEvent) => e.key === "Escape" && closeAdd()
watch(addOpen, (open) => {
  if (open) {
    setTimeout(() => {
      window.addEventListener("pointerdown", closeAdd)
      window.addEventListener("keydown", onAddKey)
    }, 0)
  } else {
    window.removeEventListener("pointerdown", closeAdd)
    window.removeEventListener("keydown", onAddKey)
  }
})

function add(t: ArtboardKind) {
  addArtboard(t)
  addOpen.value = false
}
const canEdit = () => editor.selectedArtboardId !== ""
const canUngroup = () => !!selectedArtboard.value?.groupId
function doUngroup() {
  const a = selectedArtboard.value
  if (a?.groupId) ungroup(a.groupId)
}
</script>

<template>
  <header class="flex h-12 items-center justify-between border-b border-border/60 bg-background px-4">
    <div class="flex items-center gap-2">
      <span class="inline-block size-3 rounded-[2px] bg-foreground" />
      <span class="font-mono text-sm tracking-tight">dither-ui</span>
      <span class="ml-1 rounded-full border border-border px-2 py-0.5 text-[10px] text-muted-foreground">studio</span>
    </div>

    <div class="flex items-center gap-1.5">
      <!-- Add -->
      <div class="relative">
        <button type="button" aria-haspopup="menu" :aria-expanded="addOpen" class="flex items-center gap-1.5 rounded-md bg-accent px-2.5 py-1.5 text-[11px] text-accent-foreground transition-opacity hover:opacity-90" @click="addOpen = !addOpen">
          + artboard
        </button>
        <div v-if="addOpen" role="menu" class="absolute right-0 top-full z-30 mt-1 w-32 rounded-lg border border-border bg-card p-1 shadow-[0_10px_30px_-10px_rgba(0,0,0,0.6)]" @pointerdown.stop>
          <button v-for="t in CHART_TYPES" :key="t" type="button" class="block w-full rounded-md px-2 py-1.5 text-left text-xs capitalize text-muted-foreground transition-colors hover:bg-background hover:text-foreground" @click="add(t)">{{ t }}</button>
          <div class="my-1 h-px bg-border" />
          <button v-for="t in (['avatar', 'button', 'gradient', 'image'] as const)" :key="t" type="button" class="block w-full rounded-md px-2 py-1.5 text-left text-xs capitalize text-muted-foreground transition-colors hover:bg-background hover:text-foreground" @click="add(t)">{{ t }}</button>
          <template v-if="presets.length">
            <div class="my-1 h-px bg-border" />
            <p class="px-2 py-0.5 text-[9px] uppercase tracking-widest text-muted-foreground/60">presets</p>
            <button v-for="p in presets" :key="p.name" type="button" class="block w-full truncate rounded-md px-2 py-1.5 text-left text-xs text-muted-foreground transition-colors hover:bg-background hover:text-foreground" @click="addArtboardFromPreset(p); addOpen = false">{{ p.name }}</button>
          </template>
        </div>
      </div>

      <button type="button" :disabled="!history.canUndo" title="Undo (⌘Z)" aria-label="Undo" aria-keyshortcuts="Control+Z Meta+Z" class="flex size-7 items-center justify-center rounded-md text-muted-foreground transition-colors hover:bg-card hover:text-foreground disabled:opacity-40" @click="undo">
        <svg viewBox="0 0 24 24" class="size-3.5" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 7v6h6" /><path d="M3 13a9 9 0 1 0 3-7.7L3 8" /></svg>
      </button>
      <button type="button" :disabled="!history.canRedo" title="Redo (⌘⇧Z)" aria-label="Redo" aria-keyshortcuts="Control+Shift+Z Meta+Shift+Z" class="flex size-7 items-center justify-center rounded-md text-muted-foreground transition-colors hover:bg-card hover:text-foreground disabled:opacity-40" @click="redo">
        <svg viewBox="0 0 24 24" class="size-3.5" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 7v6h-6" /><path d="M21 13a9 9 0 1 1-3-7.7L21 8" /></svg>
      </button>

      <span class="mx-1 h-4 w-px bg-border" />

      <button type="button" :disabled="!canEdit()" title="Duplicate (⌘D)" class="rounded-md px-2.5 py-1.5 text-[11px] text-muted-foreground transition-colors hover:bg-card hover:text-foreground disabled:opacity-40" @click="duplicateSelected">duplicate</button>
      <button type="button" :disabled="!canEdit()" title="Delete (⌫)" class="rounded-md px-2.5 py-1.5 text-[11px] text-muted-foreground transition-colors hover:bg-card hover:text-foreground disabled:opacity-40" @click="removeSelected">delete</button>
      <button type="button" :disabled="editor.selectedIds.length < 1" title="Group (⌘G)" class="rounded-md px-2.5 py-1.5 text-[11px] text-muted-foreground transition-colors hover:bg-card hover:text-foreground disabled:opacity-40" @click="groupSelected">group</button>
      <button v-if="canUngroup()" type="button" title="Ungroup (⌘⇧G)" class="rounded-md px-2.5 py-1.5 text-[11px] text-muted-foreground transition-colors hover:bg-card hover:text-foreground" @click="doUngroup">ungroup</button>

      <span class="mx-1 h-4 w-px bg-border" />

      <button type="button" class="flex items-center gap-1.5 rounded-md px-2.5 py-1.5 text-[11px] text-muted-foreground transition-colors hover:bg-card hover:text-foreground" @click="replay">
        <svg viewBox="0 0 24 24" class="size-3.5" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 12a9 9 0 1 1-3-6.7L21 8" /><path d="M21 3v5h-5" /></svg>
        replay
      </button>
      <button type="button" :disabled="!canData()" title="Edit the chart data" class="rounded-md px-2.5 py-1.5 text-[11px] transition-colors hover:bg-card disabled:opacity-40" :class="editor.dataOpen ? 'text-accent' : 'text-muted-foreground hover:text-foreground'" @click="editor.dataOpen = !editor.dataOpen">data</button>
      <button type="button" class="rounded-md px-2.5 py-1.5 text-[11px] text-muted-foreground transition-colors hover:bg-card hover:text-foreground" @click="emit('export')">export</button>
      <button type="button" :disabled="!editor.selectedArtboardId || pngBusy" title="Download the selected artboard as a PNG (@2x)" class="rounded-md px-2.5 py-1.5 text-[11px] text-muted-foreground transition-colors hover:bg-card hover:text-foreground disabled:opacity-40" @click="onPng">png</button>

      <span class="mx-1 h-4 w-px bg-border" />

      <button type="button" title="Download project (.json)" class="rounded-md px-2.5 py-1.5 text-[11px] text-muted-foreground transition-colors hover:bg-card hover:text-foreground" @click="exportDocument">save</button>
      <button type="button" title="Open a project (.json)" class="rounded-md px-2.5 py-1.5 text-[11px] text-muted-foreground transition-colors hover:bg-card hover:text-foreground" @click="fileInput?.click()">open</button>
      <input ref="fileInput" type="file" accept="application/json" name="open-project" class="hidden" @change="onOpenFile" />

      <button type="button" class="flex size-8 items-center justify-center rounded-md text-muted-foreground transition-colors hover:bg-card hover:text-foreground" :aria-label="dark ? 'Light' : 'Dark'" @click="toggle">
        <svg viewBox="0 0 24 24" class="size-3.5" fill="none" stroke="currentColor" stroke-width="2">
          <template v-if="dark"><circle cx="12" cy="12" r="4" /><path d="M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4" /></template>
          <path v-else d="M21 12.8A9 9 0 1 1 11.2 3 7 7 0 0 0 21 12.8z" />
        </svg>
      </button>
    </div>
  </header>
</template>

// dither-next/src/widgets/toolbar/Toolbar.tsx
"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import type { ArtboardKind } from "@/entities/artboard";
import {
  addArtboard,
  addComponentArtboard,
  addScreenArtboard,
  duplicateSelected,
  groupSelected,
  removeSelected,
  replay,
  setDataOpen,
  ungroup,
  useEditor,
} from "@/entities/editor";
import {
  COMPONENT_REGISTRY,
  type ComponentEntry,
  type ComponentGroup,
} from "@/entities/widget";
import { useHistory, redo, undo } from "@/features/history";
import { exportArtboardPng } from "@/features/export-image";
import {
  activeProjectName,
  createProject,
  deleteProject,
  exportDocument,
  importDocument,
  renameProject,
  switchProject,
  useActiveProjectId,
  useProjects,
} from "@/features/persistence";
import { addArtboardFromPreset, usePresets } from "@/features/presets";
import { CHART_TYPES } from "@/shared/config";
import { cn, routePath, useTheme } from "@/shared/lib";
import styles from "./Toolbar.module.css";

/**
 * Toolbar — the Studio top bar + floating selection toolbar. Verbatim port
 * of `src/widgets/toolbar/Toolbar.vue` (CONVERSION-GUIDE.md §11).
 *
 * Three `pointer-events-auto` groups over a `pointer-events-none` bar:
 *   1. Left: home link + project menu (switch/new/rename/save/open file/delete).
 *   2. Center: Library button → dropdown dialog (search, Canvas chart types +
 *      widget kinds + Screen, component groups, Presets).
 *   3. Right: Undo/Redo, toggle layers/inspector, theme toggle.
 *
 * A fourth element — the selection toolbar — is a fixed-bottom bar shown when
 * an artboard is selected. It is kept mounted and toggled via opacity/transform
 * classes (guide §6) to mirror the Vue `<Transition name="selection-tools">`.
 *
 * v-model:layers-open / v-model:inspector-open become controlled props
 * (`layersOpen` + `onLayersOpenChange`, `inspectorOpen` +
 * `onInspectorOpenChange`). `@export` becomes `onExport`.
 */

const CANVAS_WIDGET_KINDS = ["avatar", "button", "gradient", "image"] as const;

const GROUPS: { id: ComponentGroup; label: string }[] = [
  { id: "inputs", label: "Inputs" },
  { id: "navigation", label: "Navigation" },
  { id: "display", label: "Display" },
  { id: "overlays", label: "Overlays" },
  { id: "structure", label: "Structure" },
];

export interface ToolbarProps {
  layersOpen: boolean;
  inspectorOpen: boolean;
  onLayersOpenChange: (v: boolean) => void;
  onInspectorOpenChange: (v: boolean) => void;
  onExport: () => void;
}

export function Toolbar({
  layersOpen,
  inspectorOpen,
  onLayersOpenChange,
  onInspectorOpenChange,
  onExport,
}: ToolbarProps) {
  const { dark, toggle } = useTheme();
  const [libraryOpen, setLibraryOpen] = useState(false);
  const [projectOpen, setProjectOpen] = useState(false);
  const [query, setQuery] = useState("");
  const [pngBusy, setPngBusy] = useState(false);

  const searchRef = useRef<HTMLInputElement | null>(null);
  const fileInput = useRef<HTMLInputElement | null>(null);

  const projects = useProjects();
  const activeId = useActiveProjectId();
  const presets = usePresets();
  const { canUndo, canRedo } = useHistory();

  // Reactive editor slices for the selection toolbar.
  const selectedArtboardId = useEditor((s) => s.selectedArtboardId);
  const selectedIds = useEditor((s) => s.selectedIds);
  const dataOpen = useEditor((s) => s.dataOpen);
  const artboards = useEditor((s) => s.artboards);

  const selected = useMemo(
    () => artboards.find((a) => a.id === selectedArtboardId) ?? null,
    [artboards, selectedArtboardId],
  );

  const canEdit = selectedArtboardId !== "";
  const canData = !!selected && !selected.widget;
  const canUngroup = !!selected?.groupId;
  const selectionLabel =
    selectedIds.length > 1
      ? `${selectedIds.length} selected`
      : (selected?.name ?? "");

  const grouped = useMemo(() => {
    const q = query.trim().toLowerCase();
    const matches = (entry: ComponentEntry) =>
      !q || `${entry.label} ${entry.is}`.toLowerCase().includes(q);
    return GROUPS.map((group) => ({
      ...group,
      items: COMPONENT_REGISTRY.filter(
        (entry) => entry.group === group.id && matches(entry),
      ),
    })).filter((group) => group.items.length);
  }, [query]);

  // Mirrors Vue's `watch(libraryOpen, ...)`: focus the search input when the
  // library opens and clear the query when it closes.
  useEffect(() => {
    if (libraryOpen) {
      // requestAnimationFrame defers focus until the input is painted, the
      // React analogue of Vue's nextTick.
      const id = requestAnimationFrame(() => searchRef.current?.focus());
      return () => cancelAnimationFrame(id);
    }
    setQuery("");
  }, [libraryOpen]);

  const closeMenus = () => {
    setLibraryOpen(false);
    setProjectOpen(false);
  };

  const add = (kind: ArtboardKind) => {
    addArtboard(kind);
    closeMenus();
  };
  const addComponent = (entry: ComponentEntry) => {
    addComponentArtboard(entry);
    closeMenus();
  };
  const addScreen = () => {
    addScreenArtboard();
    closeMenus();
  };

  const doUngroup = () => {
    if (selected?.groupId) ungroup(selected.groupId);
  };

  function newProject() {
    const name = window.prompt("Project name", `Project ${projects.length + 1}`);
    if (name) createProject(name);
    closeMenus();
  }
  function rename() {
    const name = window.prompt("Rename project", activeProjectName());
    if (name) renameProject(activeId, name);
    closeMenus();
  }
  function removeProject() {
    if (
      window.confirm(`Delete “${activeProjectName()}”? This cannot be undone.`)
    ) {
      deleteProject(activeId);
    }
    closeMenus();
  }
  async function openFile(e: React.ChangeEvent<HTMLInputElement>) {
    const input = e.target;
    const file = input.files?.[0];
    if (file) await importDocument(file);
    input.value = "";
  }
  async function exportPng() {
    if (!selected || pngBusy) return;
    setPngBusy(true);
    await exportArtboardPng(selected, 2);
    setPngBusy(false);
  }

  return (
    <div className="pointer-events-none absolute inset-x-0 top-0 z-30 flex items-start justify-between gap-3 p-3">
      {/* 1. Left: home + project menu */}
      <div className="pointer-events-auto flex h-10 items-center rounded-lg border border-border/70 bg-background/95 px-1 shadow-[0_2px_8px_rgba(0,0,0,0.24)]">
        <a
          href={routePath("/")}
          className="flex h-8 items-center gap-2 rounded-md px-2.5 text-xs text-foreground transition-colors hover:bg-card"
          aria-label="dither-ui home"
        >
          <span className="size-2.5 rounded-[2px] bg-foreground" />
          <span>dither-ui</span>
        </a>
        <div className="relative border-l border-border/60 pl-1">
          <button
            type="button"
            aria-haspopup="menu"
            aria-expanded={projectOpen}
            className="flex h-8 max-w-48 items-center gap-1.5 rounded-md px-2 text-[11px] text-muted-foreground hover:bg-card hover:text-foreground"
            onClick={() => {
              setProjectOpen((v) => !v);
              setLibraryOpen(false);
            }}
          >
            <span className="truncate">{activeProjectName()}</span>
            <span aria-hidden="true">⌄</span>
          </button>
          {projectOpen && (
            <div
              role="menu"
              className="absolute left-0 top-full mt-1 w-56 rounded-lg border border-border bg-card p-1 shadow-[0_8px_24px_rgba(0,0,0,0.32)]"
            >
              {projects.map((project) => (
                <button
                  key={project.id}
                  type="button"
                  role="menuitem"
                  className={cn(
                    "flex w-full rounded-md px-2 py-1.5 text-left text-xs",
                    project.id === activeId
                      ? "bg-accent/15 text-foreground"
                      : "text-muted-foreground hover:bg-background hover:text-foreground",
                  )}
                  onClick={() => {
                    switchProject(project.id);
                    closeMenus();
                  }}
                >
                  {project.name}
                </button>
              ))}
              <div className="my-1 h-px bg-border" />
              <button type="button" role="menuitem" className={styles.menuRow} onClick={newProject}>
                New project
              </button>
              <button type="button" role="menuitem" className={styles.menuRow} onClick={rename}>
                Rename
              </button>
              <button
                type="button"
                role="menuitem"
                className={styles.menuRow}
                onClick={() => {
                  exportDocument();
                  closeMenus();
                }}
              >
                Save to file
              </button>
              <button
                type="button"
                role="menuitem"
                className={styles.menuRow}
                onClick={() => {
                  fileInput.current?.click();
                  closeMenus();
                }}
              >
                Open file
              </button>
              <div className="my-1 h-px bg-border" />
              <button
                type="button"
                role="menuitem"
                className={cn(styles.menuRow, "text-red-400")}
                onClick={removeProject}
              >
                Delete project
              </button>
            </div>
          )}
        </div>
      </div>

      {/* 2. Center: Library */}
      <div className="pointer-events-auto relative">
        <button
          type="button"
          aria-haspopup="dialog"
          aria-expanded={libraryOpen}
          className="flex h-10 items-center gap-2 rounded-lg border border-border/70 bg-background/95 px-3 text-xs text-foreground shadow-[0_2px_8px_rgba(0,0,0,0.24)] transition-colors hover:bg-card active:scale-[0.96]"
          onClick={() => {
            setLibraryOpen((v) => !v);
            setProjectOpen(false);
          }}
        >
          <span aria-hidden="true" className="text-base leading-none">
            +
          </span>{" "}
          Library
        </button>
        {libraryOpen && (
          <div
            role="dialog"
            aria-label="Component library"
            className="absolute left-1/2 top-full mt-2 flex max-h-[min(72vh,640px)] w-[420px] -translate-x-1/2 flex-col overflow-hidden rounded-lg border border-border bg-card shadow-[0_12px_36px_rgba(0,0,0,0.38)]"
          >
            <label className="border-b border-border/60 p-2">
              <span className="sr-only">Search components</span>
              <input
                ref={searchRef}
                value={query}
                onChange={(e) => setQuery(e.target.value)}
                type="search"
                name="component-search"
                placeholder="Search 55 components…"
                className="h-9 w-full rounded-md border border-border bg-background px-3 text-xs text-foreground outline-none placeholder:text-muted-foreground focus:border-accent/60"
                onKeyDown={(e) => {
                  if (e.key === "Escape") setLibraryOpen(false);
                }}
              />
            </label>
            <div className="overflow-y-auto p-2">
              {!query && (
                <section className="mb-3">
                  <p className={styles.libraryLabel}>Canvas</p>
                  <div className="grid grid-cols-3 gap-1">
                    {CHART_TYPES.map((type) => (
                      <button
                        key={type}
                        type="button"
                        className={cn(styles.libraryItem, "capitalize")}
                        onClick={() => add(type)}
                      >
                        {type} chart
                      </button>
                    ))}
                    {CANVAS_WIDGET_KINDS.map((type) => (
                      <button
                        key={type}
                        type="button"
                        className={cn(styles.libraryItem, "capitalize")}
                        onClick={() => add(type)}
                      >
                        {type}
                      </button>
                    ))}
                    <button
                      type="button"
                      className={styles.libraryItem}
                      onClick={addScreen}
                    >
                      Screen
                    </button>
                  </div>
                </section>
              )}
              {grouped.map((group) => (
                <section key={group.id} className="mb-3 last:mb-0">
                  <p className={styles.libraryLabel}>{group.label}</p>
                  <div className="grid grid-cols-2 gap-1">
                    {group.items.map((entry) => (
                      <button
                        key={entry.is}
                        type="button"
                        className={cn(styles.libraryItem, "text-left")}
                        onClick={() => addComponent(entry)}
                      >
                        <span className="block truncate text-foreground">
                          {entry.label}
                        </span>
                        <span className="block truncate text-[9px] text-muted-foreground/60">
                          {entry.is}
                        </span>
                      </button>
                    ))}
                  </div>
                </section>
              ))}
              {presets.length > 0 && !query && (
                <section>
                  <p className={styles.libraryLabel}>Presets</p>
                  {presets.map((preset) => (
                    <button
                      key={preset.name}
                      type="button"
                      className={cn(styles.libraryItem, "w-full text-left")}
                      onClick={() => {
                        addArtboardFromPreset(preset);
                        closeMenus();
                      }}
                    >
                      {preset.name}
                    </button>
                  ))}
                </section>
              )}
              {grouped.length === 0 && (
                <p className="px-2 py-8 text-center text-xs text-muted-foreground">
                  No components match “{query}”.
                </p>
              )}
            </div>
          </div>
        )}
      </div>

      {/* 3. Right: history + toggles + theme */}
      <div className="pointer-events-auto flex h-10 items-center gap-0.5 rounded-lg border border-border/70 bg-background/95 p-1 shadow-[0_2px_8px_rgba(0,0,0,0.24)]">
        <button
          type="button"
          aria-label="Undo"
          title="Undo (⌘Z)"
          disabled={!canUndo}
          className={styles.tool}
          onClick={undo}
        >
          ↶
        </button>
        <button
          type="button"
          aria-label="Redo"
          title="Redo (⌘⇧Z)"
          disabled={!canRedo}
          className={styles.tool}
          onClick={redo}
        >
          ↷
        </button>
        <span className="mx-1 h-4 w-px bg-border" />
        <button
          type="button"
          aria-label="Toggle layers"
          aria-pressed={layersOpen}
          title="Layers"
          className={styles.tool}
          onClick={() => onLayersOpenChange(!layersOpen)}
        >
          ☷
        </button>
        <button
          type="button"
          aria-label="Toggle properties"
          aria-pressed={inspectorOpen}
          title="Properties"
          className={styles.tool}
          onClick={() => onInspectorOpenChange(!inspectorOpen)}
        >
          ◫
        </button>
        <button
          type="button"
          aria-label={dark ? "Use light theme" : "Use dark theme"}
          className={styles.tool}
          onClick={toggle}
        >
          {dark ? "☀" : "◐"}
        </button>
      </div>

      {/* Selection toolbar — kept mounted, toggled via transition classes (guide §6). */}
      <div
        role="toolbar"
        aria-label="Selection actions"
        className={cn(
          "pointer-events-auto fixed left-1/2 z-30 flex h-10 -translate-x-1/2 items-center gap-0.5 rounded-lg border border-border/70 bg-background/95 p-1 shadow-[0_2px_8px_rgba(0,0,0,0.24)] transition-[transform,opacity] duration-[160ms] ease-[cubic-bezier(0.2,0,0,1)] motion-reduce:transition-none",
          canEdit
            ? "opacity-100 translate-y-0"
            : "pointer-events-none translate-y-1.5 opacity-0",
          dataOpen ? "bottom-[17rem]" : "bottom-3",
        )}
      >
        <span
          className="max-w-36 truncate px-2 text-[11px] text-foreground"
          aria-live="polite"
        >
          {selectionLabel}
        </span>
        <span className="mx-0.5 h-4 w-px bg-border" />
        <button
          type="button"
          title="Duplicate (⌘D)"
          className={cn(styles.tool, styles.wide)}
          onClick={duplicateSelected}
        >
          duplicate
        </button>
        {canUngroup ? (
          <button
            type="button"
            title="Ungroup (⌘⇧G)"
            className={cn(styles.tool, styles.wide)}
            onClick={doUngroup}
          >
            ungroup
          </button>
        ) : (
          <button
            type="button"
            title="Group (⌘G)"
            className={cn(styles.tool, styles.wide)}
            onClick={groupSelected}
          >
            group
          </button>
        )}
        <button
          type="button"
          title="Delete (⌫)"
          className={cn(styles.tool, styles.wide, "text-red-400")}
          onClick={removeSelected}
        >
          delete
        </button>
        <span className="mx-0.5 h-4 w-px bg-border" />
        <button
          type="button"
          title="Replay animation"
          className={styles.tool}
          aria-label="Replay animation"
          onClick={replay}
        >
          ↻
        </button>
        {canData && (
          <button
            type="button"
            className={cn(styles.tool, styles.wide, dataOpen && "bg-card text-foreground")}
            aria-pressed={dataOpen}
            onClick={() => setDataOpen(!dataOpen)}
          >
            data
          </button>
        )}
        <button
          type="button"
          className={cn(styles.tool, styles.wide)}
          onClick={onExport}
        >
          code
        </button>
        <button
          type="button"
          disabled={pngBusy}
          className={cn(styles.tool, styles.wide)}
          onClick={exportPng}
        >
          {pngBusy ? "saving…" : "png"}
        </button>
      </div>

      <input
        ref={fileInput}
        type="file"
        accept="application/json"
        name="open-project"
        className="hidden"
        onChange={openFile}
      />
    </div>
  );
}
